### ISSUE TITLE
vite 문서 번역 해주셔서 감사합니다. 

### ISSUE THREAD

**Issue by easylogic** [vitejs/docs-ko#185]
최근에 vite 를 많이 쓸려고 하고 있는데, 번역 문서가 있으니 너무 좋네요. 

정말 정말 감사합니다.

**Comment by Gumball12** [comment]
읽어주셔서 감사합니다. 도움이 되셨다니 저도 정말 뿌듯하고 기쁘게 생각합니다.
더욱 많은 분들에게 도움이 될 수 있도록 앞으로도 지속적으로 관리하도록 하겠습니다. 🙂
